name: Update stats

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          version: lts/*
          cache: 'yarn'
      - name: Install pug
        run: yarn ci
      - name: Compile README
        run: yarn pug templates/README.pug -E md -o .
      - uses: stefanzweifel/git-auto-commit-action@v4

